---
# handlers file for ansible-nginx-uwsgi-supervisor
- name: restart uwsgi app
  supervisorctl: name={{ uwsgi_app_service_name }} state=restarted config=/etc/supervisor/supervisor.conf

- name: start supervisord
  service: name=supervisor state=started

- name: start supervisord
  service: name=supervisor state=started

- name: restart supervisord
  service: name=supervisor state=restarted

- name: restart nginx
  service: name=nginx state=restarted
